### ISSUE TITLE
libs index.ts is missing from the TypeScript compilation

### ISSUE THREAD

**Issue by marcintokarski** [Coly010/example-nx-ng-mfe#1]
Hello,
I have a problem with start application,  bellow error occured after `nx serve`.

.`./libs/launcher/src/index.ts - Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: /marcin/workspace/example-nx-ng-mfe/libs/launcher/src/index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at C:\marcin\workspace\example-nx-ng-mfe\node_modules\@ngtools\webpack\src\ivy\loader.js:64:26`

`../libs/shared/data-access/auth/src/index.ts - Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: /marcin/workspace/example-nx-ng-mfe/libs/shared/data-access/auth/src/index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at C:\marcin\workspace\example-nx-ng-mfe\node_modules\@ngtools\webpack\src\ivy\loader.js:64:26`

I have the same problem in my repo after migrate to nx 13.10.2 and change mfe config to `withModuleFederation`  feature, which is great 👍 but unfortunatelly seems doesn't work. Could you help me?

**Comment by Coly010** [comment]
1.Clone the repository
2.Run npm install
3.Run nx serve-mfe static-host
4.Navigate a browser to http://localhost:4200

**Comment by Coly010** [comment]
I can't reproduce, even with a fresh clone

**Comment by marcintokarski** [comment]
I did just that. Fresh clone, npm ci / install. I still have errors :( Additionally I did that on 2 computers. Is it OS related problem, maybe? I'm running on windows.

**Comment by Coly010** [comment]
It would be the biggest difference between my test and yours. I have a windows vm, I’ll give it a go over the weekend

**Comment by marcintokarski** [comment]
👍 If I could help please let me know. I'm waiting for your investigation ;)

**Comment by ak274** [comment]
I have faced the same issue. Raised a Bug on NX repo:-- [https://github.com/nrwl/nx/issues/9861](https://github.com/nrwl/nx/issues/9861)

**Comment by Coly010** [comment]
Looks like a windows issue. I have a PR on Nx now to fix https://github.com/nrwl/nx/pull/9881
